"""kural katalogu veri modeli

Revision ID: b413bb80a4bd
Revises: 
Create Date: 2026-08-06 09:08:23.079293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b413bb80a4bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bina',
    sa.Column('bina_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bina_id')
    )
    op.create_table('donem',
    sa.Column('donem_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('tercih_son_tarihi', sa.Date(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('donem_id')
    )
    op.create_table('kural',
    sa.Column('kural_id', sa.Integer(), nullable=False),
    sa.Column('kimlik', sa.String(), nullable=False),
    sa.Column('tip', sa.Enum('ZORUNLU', 'ESNEK', name='kuraltipi'), nullable=False),
    sa.Column('parametreler', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agirlik', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kural_id'),
    sa.UniqueConstraint('kimlik')
    )
    op.create_table('ozel_gun',
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tarih')
    )
    op.create_table('vardiya_tipi',
    sa.Column('vardiya_tipi_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('baslangic_saati', sa.Time(), nullable=False),
    sa.Column('bitis_saati', sa.Time(), nullable=False),
    sa.Column('sure_saat', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('gece_mi', sa.Boolean(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vardiya_tipi_id')
    )
    op.create_table('yetkinlik',
    sa.Column('yetkinlik_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aciklama', sa.String(), nullable=True),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('yetkinlik_id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('cizelge_surumu',
    sa.Column('surum_id', sa.Integer(), nullable=False),
    sa.Column('donem_id', sa.Integer(), nullable=False),
    sa.Column('surum_no', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('TASLAK', 'COZULDU', 'YAYINLANDI', 'ARSIV', name='cizelgesurumudurumu'), nullable=False),
    sa.Column('onceki_surum_id', sa.Integer(), nullable=True),
    sa.Column('yayin_zamani', sa.DateTime(), nullable=True),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donem_id'], ['donem.donem_id'], ),
    sa.ForeignKeyConstraint(['onceki_surum_id'], ['cizelge_surumu.surum_id'], ),
    sa.PrimaryKeyConstraint('surum_id')
    )
    op.create_table('gorev_noktasi',
    sa.Column('nokta_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('bina_id', sa.Integer(), nullable=True),
    sa.Column('onkosul_yetkinlik_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bina_id'], ['bina.bina_id'], ),
    sa.ForeignKeyConstraint(['onkosul_yetkinlik_id'], ['yetkinlik.yetkinlik_id'], ),
    sa.PrimaryKeyConstraint('nokta_id')
    )
    op.create_table('personel',
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(), nullable=False),
    sa.Column('sicil_no', sa.String(), nullable=False),
    sa.Column('haftalik_hedef_saat', sa.Integer(), nullable=False),
    sa.Column('sabit_vardiya_tipi_id', sa.Integer(), nullable=True),
    sa.Column('aktif_baslangic', sa.Date(), nullable=False),
    sa.Column('aktif_bitis', sa.Date(), nullable=True),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sabit_vardiya_tipi_id'], ['vardiya_tipi.vardiya_tipi_id'], ),
    sa.PrimaryKeyConstraint('personel_id'),
    sa.UniqueConstraint('sicil_no')
    )
    op.create_table('atama',
    sa.Column('atama_id', sa.Integer(), nullable=False),
    sa.Column('surum_id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('vardiya_tipi_id', sa.Integer(), nullable=False),
    sa.Column('nokta_id', sa.Integer(), nullable=False),
    sa.Column('kilitli', sa.Boolean(), nullable=False),
    sa.Column('kaynak', sa.Enum('COZUCU', 'MANUEL', name='atamakaynagi'), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nokta_id'], ['gorev_noktasi.nokta_id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.personel_id'], ),
    sa.ForeignKeyConstraint(['surum_id'], ['cizelge_surumu.surum_id'], ),
    sa.ForeignKeyConstraint(['vardiya_tipi_id'], ['vardiya_tipi.vardiya_tipi_id'], ),
    sa.PrimaryKeyConstraint('atama_id'),
    sa.UniqueConstraint('surum_id', 'personel_id', 'tarih', name='uq_atama_surum_personel_tarih')
    )
    op.create_table('cozum_isi',
    sa.Column('is_id', sa.Integer(), nullable=False),
    sa.Column('surum_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('KUYRUKTA', 'ON_KONTROL', 'COZULUYOR', 'TAMAMLANDI', 'UYARILI', 'BASARISIZ', 'IPTAL', name='cozumisidurumu'), nullable=False),
    sa.Column('baslangic_zamani', sa.DateTime(), nullable=False),
    sa.Column('bitis_zamani', sa.DateTime(), nullable=True),
    sa.Column('sure_saniye', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('zaman_limiti_saniye', sa.Integer(), nullable=False),
    sa.Column('en_iyi_ceza', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ceza_dokumu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kural_anlik_goruntu', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hata_mesaji', sa.String(), nullable=True),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['surum_id'], ['cizelge_surumu.surum_id'], ),
    sa.PrimaryKeyConstraint('is_id')
    )
    op.create_table('kapsama_acigi',
    sa.Column('acik_id', sa.Integer(), nullable=False),
    sa.Column('surum_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('vardiya_tipi_id', sa.Integer(), nullable=False),
    sa.Column('nokta_id', sa.Integer(), nullable=False),
    sa.Column('eksik_sayi', sa.Integer(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nokta_id'], ['gorev_noktasi.nokta_id'], ),
    sa.ForeignKeyConstraint(['surum_id'], ['cizelge_surumu.surum_id'], ),
    sa.ForeignKeyConstraint(['vardiya_tipi_id'], ['vardiya_tipi.vardiya_tipi_id'], ),
    sa.PrimaryKeyConstraint('acik_id')
    )
    op.create_table('musaitlik',
    sa.Column('musaitlik_id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('dilim', sa.Enum('TAM_GUN', 'OGLEDEN_ONCE', 'OGLEDEN_SONRA', name='musaitlikdilimi'), nullable=False),
    sa.Column('tip', sa.Enum('YILLIK_IZIN', 'RAPOR', 'EGITIM', 'MAZERET', name='musaitliktipi'), nullable=False),
    sa.Column('not', sa.String(), nullable=True),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.personel_id'], ),
    sa.PrimaryKeyConstraint('musaitlik_id')
    )
    op.create_table('personel_yetkinlik',
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('yetkinlik_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.personel_id'], ),
    sa.ForeignKeyConstraint(['yetkinlik_id'], ['yetkinlik.yetkinlik_id'], ),
    sa.PrimaryKeyConstraint('personel_id', 'yetkinlik_id')
    )
    op.create_table('talep',
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('nokta_id', sa.Integer(), nullable=False),
    sa.Column('vardiya_tipi_id', sa.Integer(), nullable=False),
    sa.Column('gun_tipi', sa.Enum('HAFTA_ICI', 'HAFTA_SONU', 'RESMI_TATIL', name='guntipi'), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('gereken_sayi', sa.Integer(), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nokta_id'], ['gorev_noktasi.nokta_id'], ),
    sa.ForeignKeyConstraint(['vardiya_tipi_id'], ['vardiya_tipi.vardiya_tipi_id'], ),
    sa.PrimaryKeyConstraint('talep_id')
    )
    op.create_table('tercih',
    sa.Column('tercih_id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('donem_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tip', sa.Enum('CALISMAMA', 'VARDIYA_TIPI_TERCIHI', name='tercihtipi'), nullable=False),
    sa.Column('vardiya_tipi_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI', name='tercihdurumu'), nullable=False),
    sa.Column('olusturma_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncelleme_zamani', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donem_id'], ['donem.donem_id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.personel_id'], ),
    sa.ForeignKeyConstraint(['vardiya_tipi_id'], ['vardiya_tipi.vardiya_tipi_id'], ),
    sa.PrimaryKeyConstraint('tercih_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tercih')
    op.drop_table('talep')
    op.drop_table('personel_yetkinlik')
    op.drop_table('musaitlik')
    op.drop_table('kapsama_acigi')
    op.drop_table('cozum_isi')
    op.drop_table('atama')
    op.drop_table('personel')
    op.drop_table('gorev_noktasi')
    op.drop_table('cizelge_surumu')
    op.drop_table('yetkinlik')
    op.drop_table('vardiya_tipi')
    op.drop_table('ozel_gun')
    op.drop_table('kural')
    op.drop_table('donem')
    op.drop_table('bina')
    # ### end Alembic commands ###
    # Alembic autogenerate, postgres ENUM tiplerini downgrade'de birakmaz; elle eklenmistir.
    for enum_adi in (
        'kuraltipi',
        'cizelgesurumudurumu',
        'atamakaynagi',
        'cozumisidurumu',
        'musaitlikdilimi',
        'musaitliktipi',
        'tercihtipi',
        'tercihdurumu',
        'guntipi',
    ):
        sa.Enum(name=enum_adi).drop(op.get_bind(), checkfirst=True)
